builds:
  - binary: target
    id: target
    ldflags:
      - "-X github.com/adfinis/baoctx/cmd.version={{.Version}}"
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

checksum:
  name_template: "checksums.txt"
